### ISSUE TITLE
Seg Fault on Error Log

### ISSUE THREAD

**Issue by ZacharyBenamram** [summerwind/actions-runner-controller#153]
Looks as if there is a nil pointer dereference exception when logging in NewClient in github.go

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x13080f7]

goroutine 1 [running]:
github.com/summerwind/actions-runner-controller/github.(*Config).NewClient(0xc0003cadc0, 0xc0000c0010, 0x2, 0x2)
	/workspace/github/github.go:50 +0x707
main.main()
	/workspace/main.go:85 +0x4eb
```

**Comment by mumoshu** [comment]
@ZacharyBenamram Thanks for reporting! This is going to be fixed via #154
