### ISSUE TITLE
2.274.2 runner is not working on v0.13.1

### ISSUE THREAD

**Issue by 0x77dev** [summerwind/actions-runner-controller#212]
## Config
```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  name: "{{ .Release.Name }}-runner-{{ .Values.runnerGroup }}"
spec:
  repository: "{{.Values.repository}}"
  labels:
    - {{ .Values.runnerGroup }}
```

## Command used to install controller
```shell
➜ kubectl apply -f https://github.com/summerwind/actions-runner-controller/releases/download/v0.13.1/actions-runner-controller.yaml
```

## Stacktrace

```stacktrace
│ Github endpoint URL https://github.com/                                                                                                                                                         │
│ --------------------------------------------------------------------------------                                                                                                                │
│ |        ____ _ _   _   _       _          _        _   _                      |                                                                                                                │
│ |       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |                                                                                                                │
│ |      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |                                                                                                                │
│ |      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |                                                                                                                │
│ |       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |                                                                                                                │
│ |                                                                              |                                                                                                                │
│ |                       Self-hosted runner registration                        |                                                                                                                │
│ |                                                                              |                                                                                                                │
│ --------------------------------------------------------------------------------                                                                                                                │
│ # Authentication                                                                                                                                                                                │
│ √ Connected to GitHub                                                                                                                                                                           │
│ # Runner Registration                                                                                                                                                                           │
│ A runner exists with the same name                                                                                                                                                              │
│ √ Successfully replaced the runner                                                                                                                                                              │
│ √ Runner connection is good                                                                                                                                                                     │
│ # Runner settings                                                                                                                                                                               │
│ √ Settings Saved.                                                                                                                                                                               │
│ 16c16                                                                                                                                                                                           │
│ < ./externals/node12/bin/node ./bin/RunnerService.js &                                                                                                                                          │
│ ---                                                                                                                                                                                             │
│ > ./externals/node12/bin/node ./bin/RunnerService.js $* &                                                                                                                                       │
│ 20c20                                                                                                                                                                                           │
│ < wait $PID                                                                                                                                                                                     │
│ ---                                                                                                                                                                                             │
│ > wait $PID                                                                                                                                                                                     │
│ \ No newline at end of file                                                                                                                                                                     │
│ 27c27                                                                                                                                                                                           │
│ <                 listener = childProcess.spawn(listenerExePath, ['run'], { env: process.env });                                                                                                │
│ ---                                                                                                                                                                                             │
│ >                 listener = childProcess.spawn(listenerExePath, ['run'].concat(process.argv.slice(3)), { env: process.env });                                                                  │
│ 30c30                                                                                                                                                                                           │
│ <                 listener = childProcess.spawn(listenerExePath, ['run', '--startuptype', 'service'], { env: process.env });                                                                    │
│ ---                                                                                                                                                                                             │
│ >                 listener = childProcess.spawn(listenerExePath, ['run', '--startuptype', 'service'].concat(process.argv.slice(2)), { env: process.env });                                      │
│ 34c34                                                                                                                                                                                           │
│ <                                                                                                                                                                                               │
│ ---                                                                                                                                                                                             │
│ >                                                                                                                                                                                               │
│ 59c59                                                                                                                                                                                           │
│ <                                                                                                                                                                                               │
│ ---                                                                                                                                                                                             │
│ >                                                                                                                                                                                               │
│ 91c91                                                                                                                                                                                           │
│ < });                                                                                                                                                                                           │
│ ---                                                                                                                                                                                             │
│ > });                                                                                                                                                                                           │
│ \ No newline at end of file                                                                                                                                                                     │
│ .path=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin                                                                                                                              │
│ Starting Runner listener with startup type: service                                                                                                                                             │
│ Started listener process                                                                                                                                                                        │
│ Started running service                                                                                                                                                                         │
│ √ Connected to GitHub                                                                                                                                                                           │
│ 2020-11-26 09:23:01Z: Listening for Jobs                                                                                                                                                        │
│ Runner update in progress, do not shutdown runner.                                                                                                                                              │
│ Downloading 2.274.2 runner                                                                                                                                                                      │
│ Waiting for current job finish running.                                                                                                                                                         │
│ Generate and execute update script.                                                                                                                                                             │
│ Runner will exit shortly for update, should back online within 10 seconds.                                                                                                                      │
│ renamed '/runner/_diag/SelfUpdate-20201126-092309.log' -> '/runner/_diag/SelfUpdate-20201126-092309.log.failed'                                                                                 │
│ Runner listener exited with error code 4                                                                                                                                                        │
│ Runner listener exit with undefined return code, re-launch runner in 5 seconds.                                                                                                                 │
│ Starting Runner listener with startup type: service                                                                                                                                             │
│ Started listener process                                                                                                                                                                        │
│ events.js:187                                                                                                                                                                                   │
│       throw er; // Unhandled 'error' event                                                                                                                                                      │
│       ^                                                                                                                                                                                         │
│ Error: spawn /runner/bin/Runner.Listener ENOENT                                                                                                                                                 │
│     at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)                                                                                                                   │
│     at onErrorNT (internal/child_process.js:456:16)                                                                                                                                             │
│     at processTicksAndRejections (internal/process/task_queues.js:80:21)                                                                                                                        │
│ Emitted 'error' event on ChildProcess instance at:                                                                                                                                              │
│     at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)                                                                                                                   │
│     at onErrorNT (internal/child_process.js:456:16)                                                                                                                                             │
│     at processTicksAndRejections (internal/process/task_queues.js:80:21) {                                                                                                                      │
│   errno: 'ENOENT',                                                                                                                                                                              │
│   code: 'ENOENT',                                                                                                                                                                               │
│   syscall: 'spawn /runner/bin/Runner.Listener',                                                                                                                                                 │
│   path: '/runner/bin/Runner.Listener',                                                                                                                                                          │
│   spawnargs: [ 'run', '--startuptype', 'service', '--once' ]                                                                                                                                    │
│ }                                                                                                                                                                                               │
│ stream closed
```

## SelfUpdate log file
```log
[2020-11-26 09:28:06-9447] --------whoami--------
runner
[2020-11-26 09:28:06-9474] --------whoami--------
[2020-11-26 09:28:06-9485] Waiting for Runner.Listener (91) to complete
[2020-11-26 09:28:06-9496] Process 91 still running
[2020-11-26 09:28:08-9523] Process 91 finished running
[2020-11-26 09:28:08-9537] Sleep 1 more second to make sure process exited
[2020-11-26 09:28:09-9564] move /runner/bin /runner/bin.2.274.1
created directory '/runner/bin.2.274.1'
renamed '/runner/bin/Microsoft.CSharp.dll' -> '/runner/bin.2.274.1/Microsoft.CSharp.dll'
renamed '/runner/bin/Microsoft.IdentityModel.Logging.dll' -> '/runner/bin.2.274.1/Microsoft.IdentityModel.Logging.dll'
renamed '/runner/bin/Microsoft.IdentityModel.Tokens.dll' -> '/runner/bin.2.274.1/Microsoft.IdentityModel.Tokens.dll'
renamed '/runner/bin/Microsoft.VisualBasic.Core.dll' -> '/runner/bin.2.274.1/Microsoft.VisualBasic.Core.dll'
renamed '/runner/bin/Microsoft.VisualBasic.dll' -> '/runner/bin.2.274.1/Microsoft.VisualBasic.dll'
renamed '/runner/bin/Microsoft.Win32.Primitives.dll' -> '/runner/bin.2.274.1/Microsoft.Win32.Primitives.dll'
renamed '/runner/bin/Microsoft.Win32.Registry.dll' -> '/runner/bin.2.274.1/Microsoft.Win32.Registry.dll'
renamed '/runner/bin/Minimatch.dll' -> '/runner/bin.2.274.1/Minimatch.dll'
renamed '/runner/bin/Newtonsoft.Json.Bson.dll' -> '/runner/bin.2.274.1/Newtonsoft.Json.Bson.dll'
renamed '/runner/bin/Newtonsoft.Json.dll' -> '/runner/bin.2.274.1/Newtonsoft.Json.dll'
renamed '/runner/bin/Runner.Common.deps.json' -> '/runner/bin.2.274.1/Runner.Common.deps.json'
renamed '/runner/bin/Runner.Common.dll' -> '/runner/bin.2.274.1/Runner.Common.dll'
renamed '/runner/bin/Runner.Listener' -> '/runner/bin.2.274.1/Runner.Listener'
renamed '/runner/bin/Runner.Listener.deps.json' -> '/runner/bin.2.274.1/Runner.Listener.deps.json'
renamed '/runner/bin/Runner.Listener.dll' -> '/runner/bin.2.274.1/Runner.Listener.dll'
renamed '/runner/bin/Runner.Listener.runtimeconfig.json' -> '/runner/bin.2.274.1/Runner.Listener.runtimeconfig.json'
renamed '/runner/bin/Runner.PluginHost' -> '/runner/bin.2.274.1/Runner.PluginHost'
renamed '/runner/bin/Runner.PluginHost.deps.json' -> '/runner/bin.2.274.1/Runner.PluginHost.deps.json'
renamed '/runner/bin/Runner.PluginHost.dll' -> '/runner/bin.2.274.1/Runner.PluginHost.dll'
renamed '/runner/bin/Runner.PluginHost.runtimeconfig.json' -> '/runner/bin.2.274.1/Runner.PluginHost.runtimeconfig.json'
renamed '/runner/bin/Runner.Plugins.deps.json' -> '/runner/bin.2.274.1/Runner.Plugins.deps.json'
renamed '/runner/bin/Runner.Plugins.dll' -> '/runner/bin.2.274.1/Runner.Plugins.dll'
renamed '/runner/bin/Runner.Sdk.deps.json' -> '/runner/bin.2.274.1/Runner.Sdk.deps.json'
renamed '/runner/bin/Runner.Sdk.dll' -> '/runner/bin.2.274.1/Runner.Sdk.dll'
renamed '/runner/bin/Runner.Worker' -> '/runner/bin.2.274.1/Runner.Worker'
renamed '/runner/bin/Runner.Worker.deps.json' -> '/runner/bin.2.274.1/Runner.Worker.deps.json'
renamed '/runner/bin/Runner.Worker.dll' -> '/runner/bin.2.274.1/Runner.Worker.dll'
renamed '/runner/bin/Runner.Worker.runtimeconfig.json' -> '/runner/bin.2.274.1/Runner.Worker.runtimeconfig.json'
renamed '/runner/bin/RunnerService.js.bak' -> '/runner/bin.2.274.1/RunnerService.js.bak'
renamed '/runner/bin/SOS_README.md' -> '/runner/bin.2.274.1/SOS_README.md'
renamed '/runner/bin/Sdk.deps.json' -> '/runner/bin.2.274.1/Sdk.deps.json'
renamed '/runner/bin/Sdk.dll' -> '/runner/bin.2.274.1/Sdk.dll'
renamed '/runner/bin/System.AppContext.dll' -> '/runner/bin.2.274.1/System.AppContext.dll'
renamed '/runner/bin/System.Buffers.dll' -> '/runner/bin.2.274.1/System.Buffers.dll'
renamed '/runner/bin/System.Collections.Concurrent.dll' -> '/runner/bin.2.274.1/System.Collections.Concurrent.dll'
renamed '/runner/bin/System.Collections.Immutable.dll' -> '/runner/bin.2.274.1/System.Collections.Immutable.dll'
renamed '/runner/bin/System.Collections.NonGeneric.dll' -> '/runner/bin.2.274.1/System.Collections.NonGeneric.dll'
renamed '/runner/bin/System.Collections.Specialized.dll' -> '/runner/bin.2.274.1/System.Collections.Specialized.dll'
renamed '/runner/bin/System.Collections.dll' -> '/runner/bin.2.274.1/System.Collections.dll'
renamed '/runner/bin/System.ComponentModel.Annotations.dll' -> '/runner/bin.2.274.1/System.ComponentModel.Annotations.dll'
renamed '/runner/bin/System.ComponentModel.DataAnnotations.dll' -> '/runner/bin.2.274.1/System.ComponentModel.DataAnnotations.dll'
```

**Comment by bjw-s** [comment]
I'm seeing the same behavior 🙁

**Comment by mumoshu** [comment]
@0x77dev @bjw-s Hey! Took too much time to confirm this myself, but I've updated `summerwind/actions-runner:latest` a week ago and that should fix the issue for you, too.

The new image should be automatically pulled once your runner pod is recreated.

If it's stuck on older images, you can just manually remove runner pods with `kubectl delete po` so that the runner controller recreates them, as the runner pod is given `imagePullPolicy: Always` by default. You can confirm that by running something like:

```
$ kubectl get po | grep $YOUR_RUNNERDEPLOY_NAME

$ kubectl get po example-runnerdeploy-bqhf5-z9lgg -o yaml | grep -A 5 image: 
*snip*
    image: summerwind/actions-runner:latest
    imagePullPolicy: Always
    name: runner
    resources: {}
    securityContext: {}
    terminationMessagePath: /dev/termination-log
*snip*
    image: docker.io/summerwind/actions-runner:latest
    imageID: docker.io/summerwind/actions-runner@sha256:eefeb25e94437805e30e6d0ba0b95f2ddfb1c36cd0c66ea847826f175c9edfa6
    lastState: {}
    name: runner
    ready: true
    restartCount: 0
*snip*
```

As you can see in the above example, it should work if the imageID points to `sha256:eefeb25e94437805e30e6d0ba0b95f2ddfb1c36cd0c66ea847826f175c9edfa6`.

**Comment by 0x77dev** [comment]
@mumoshu Yup, all works 🥳, thanks for feedback.
